#!/bin/sh

# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Stephane Bocquet <stephane_bocquet@hotmail.com>
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c) 2011 Stephane Bocquet
# @copyright Copyright (c) 2011-2012 Marcel Beck
# @copyright Copyright (c) 2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

# Only if enabled
if [ "$(omv_config_get "//services/greyhole/enable")" != "1" ]; then
    exit 0
fi

OMV_SAMBA_CONFIG=${OMV_SAMBA_CONFIG:-"/etc/samba/smb.conf"}

echo "#======================= Greyhole Shares =======================" >> ${OMV_SAMBA_CONFIG}

index=$(omv_config_get_count "//services/greyhole/smb_shares/share")
while [ ${index} -gt 0 ]
do
    # Get the shared folder reference and path
    smb_share_ref=$(omv_config_get "//services/greyhole/smb_shares/share[position()=${index}]/smbref")
    smb_share_name=$(omv_config_get "//services/smb/shares/share[uuid='${smb_share_ref}']/name")

    xmlstarlet sel -t -m "//services/greyhole/smb_shares/share[position()=${index}]" \
      -o "[${smb_share_name}]" -n \
      -o "dfree command = /usr/bin/greyhole-dfree" -n \
      -o "vfs objects = greyhole" -n \
      ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_SAMBA_CONFIG}

    index=$(( ${index} - 1 ))
done

if [ "$(omv_config_get "//services/greyhole/trash_share")" != "0" ]; then

	trashsharepath=$(omv_config_get "//services/greyhole/trash_share_path")

	cat <<EOF >> ${OMV_SAMBA_CONFIG}
[Greyhole Trash]
comment = Greyhole Trash
path = "${trashsharepath}"
dfree command = /usr/bin/greyhole-dfree
vfs objects = greyhole
EOF

fi