#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Stephane Bocquet <stephane_bocquet@hotmail.com>
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c) 2011 Stephane Bocquet
# @copyright Copyright (c) 2012 Marcel Beck
# @copyright Copyright (c) 2014-2016 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

GREYHOLE_EXTENSIONSDIR=${GREYHOLE_EXTENSIONSDIR:-"${OMV_MKCONF_SCRIPTS_DIR}/greyhole.d"}
GREYHOLE_CONFIG="/etc/greyhole.conf"

SERVICE_XPATH_NAME="greyhole"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME"

# Enable/disable service
if [ "$(omv_config_get "${SERVICE_XPATH}/enable")" != "1" ]; then
    echo "# Stop/Disable Greyhole disabled"
    deb-systemd-invoke stop ${SERVICE_XPATH_NAME}.service >/dev/null || true
    deb-systemd-helper disable ${SERVICE_XPATH_NAME}.service >/dev/null || true
    exit 0
fi

pool_disk_count=$(omv_config_get_count "${SERVICE_XPATH}/pool_disks/disk")
if [ ${pool_disk_count} -eq 0 ]; then
    echo "# Stop/Disable Greyhole: No Pool Disks"
    deb-systemd-invoke stop ${SERVICE_XPATH_NAME}.service >/dev/null || true
    deb-systemd-helper disable ${SERVICE_XPATH_NAME}.service >/dev/null || true
    exit 0
fi

# smb_share_count=$(omv_config_get_count "${SERVICE_XPATH}/smb_shares/share")
# if [ ${smb_share_count} -eq 0 ]; then
#   echo "# Stop/Disable Greyhole: No SMB Shares"
#   deb-systemd-invoke stop ${SERVICE_XPATH_NAME}.service >/dev/null || true
#   deb-systemd-helper disable ${SERVICE_XPATH_NAME}.service >/dev/null || true
#   exit 0
# fi

echo "# Stop Greyhole"
deb-systemd-invoke stop ${SERVICE_XPATH_NAME}.service >/dev/null || true

cat /dev/null > ${GREYHOLE_CONFIG}
run-parts ${GREYHOLE_EXTENSIONSDIR}

omv-mkconf samba

echo "# Start/Enable Greyhole"
deb-systemd-helper enable ${SERVICE_XPATH_NAME}.service >/dev/null || true
deb-systemd-invoke start ${SERVICE_XPATH_NAME}.service >/dev/null || true
