#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @author    Stéphane Bocquet <stephane_bocquet@hotmail.com>
# @copyright Copyright (c) 2011 Marcel Beck
# @copyright Copyright (c) 2011 Stéphane Bocquet
# @copyright Copyright (c) 2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
    if [ -z "$2" ]; then
        echo "Updating init script links and actions"
        invoke-rc.d --force greyhole stop &>/dev/null
        update-rc.d greyhole disable &>/dev/null
    fi

    # Check for XML config
    if ! omv_config_exists "/config/services/greyhole"; then

        echo "Creating Initial Configuration"
        object="<enable>0</enable>"
        object="${object}<email_to>root</email_to>"
        object="${object}<log_level>INFO</log_level>"
        object="${object}<greyhole_log_file>/var/log/greyhole.log</greyhole_log_file>"
        object="${object}<delete_moves_to_trash>1</delete_moves_to_trash>"
        object="${object}<balance_modified_files>0</balance_modified_files>"
        object="${object}<df_cache_time>15</df_cache_time>"
        object="${object}<log_memory_usage>0</log_memory_usage>"
        object="${object}<check_for_open_files>1</check_for_open_files>"
        object="${object}<pool_disks></pool_disks>"
        object="${object}<smb_shares></smb_shares>"
        object="${object}<trash_share></trash_share>"
        object="${object}<trash_share_ref></trash_share_ref>"
        object="${object}<trash_share_path></trash_share_path>"
        object="${object}<trash_write></trash_write>"
        object="${object}<extraoptions></extraoptions>"
        object="${object}<db_engine>mysql</db_engine>"
        object="${object}<db_host>localhost</db_host>"
        object="${object}<db_user>greyhole</db_user>"
        object="${object}<db_pass>openmediavault</db_pass>"
        object="${object}<db_name>greyhole</db_name>"
        object="${object}<smb_mount_enable>0</smb_mount_enable>"
        object="${object}<smb_mount_username></smb_mount_username>"
        object="${object}<smb_mount_password></smb_mount_password>"

        omv_config_add_element "/config/services" "greyhole" "${object}" true
    fi

    #update-rc.d mountsmb_locally defaults

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
