#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @author    Stéphane Bocquet <stephane_bocquet@hotmail.com>
# @copyright Copyright (c) 2011 Marcel Beck
# @copyright Copyright (c) 2011 Stéphane Bocquet
# @copyright Copyright (c) 2014-2016 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="greyhole"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

case "$1" in
    configure)
        if [ -z "$2" ]; then
            echo "Updating init script links and actions"
            deb-systemd-invoke stop ${SERVICE_XPATH_NAME}.service >/dev/null || true
            deb-systemd-helper disable ${SERVICE_XPATH_NAME}.service >/dev/null || true
        fi

        # Check for XML config
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            echo "Initialize configuration"
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "email_to" "root"
            omv_config_add_element "${SERVICE_XPATH}" "log_level" "INFO"
            omv_config_add_element "${SERVICE_XPATH}" "greyhole_log_file" "/var/log/greyhole.log"
            omv_config_add_element "${SERVICE_XPATH}" "delete_moves_to_trash" "1"
            omv_config_add_element "${SERVICE_XPATH}" "balance_modified_files" "0"
            omv_config_add_element "${SERVICE_XPATH}" "df_cache_time" "15"
            omv_config_add_element "${SERVICE_XPATH}" "log_memory_usage" "0"
            omv_config_add_element "${SERVICE_XPATH}" "check_for_open_files" "1"
            omv_config_add_element "${SERVICE_XPATH}" "pool_disks" ""
            omv_config_add_element "${SERVICE_XPATH}" "smb_shares" ""
            omv_config_add_element "${SERVICE_XPATH}" "trash_share" ""
            omv_config_add_element "${SERVICE_XPATH}" "trash_share_ref" ""
            omv_config_add_element "${SERVICE_XPATH}" "trash_share_path" ""
            omv_config_add_element "${SERVICE_XPATH}" "trash_write" ""
            omv_config_add_element "${SERVICE_XPATH}" "extraoptions" ""
            omv_config_add_element "${SERVICE_XPATH}" "db_engine" "mysql"
            omv_config_add_element "${SERVICE_XPATH}" "db_host" "localhost"
            omv_config_add_element "${SERVICE_XPATH}" "db_user" "greyhole"
            omv_config_add_element "${SERVICE_XPATH}" "db_pass" "openmediavault"
            omv_config_add_element "${SERVICE_XPATH}" "db_name" "greyhole"
            omv_config_add_element "${SERVICE_XPATH}" "smb_mount_enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "smb_mount_username" ""
            omv_config_add_element "${SERVICE_XPATH}" "smb_mount_password" ""
            omv_config_add_element "${SERVICE_XPATH}" "ignores" ""
        fi

        #deb-systemd-helper enable mountsmb_locally.service

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
