#!/bin/sh
#
# This file is part of OpenMediaVault-greyhole.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @author    Stéphane Bocquet <stephane_bocquet@hotmail.com>
# @copyright Copyright (c) 2011 Marcel Beck
# @copyright Copyright (c) 2011 Stéphane Bocquet
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

case "$1" in
	purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
		# Stop service
		invoke-rc.d --quiet greyhole stop &>/dev/null
	;;

	upgrade)
	;;

	*)
		echo "postrm called with unknown argument '$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
