#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c) 2012 Marcel Beck
# @copyright Copyright (c) 2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

GREYHOLE_CONFIG="/etc/greyhole.conf"

xmlstarlet sel -t -m "//services/greyhole" \
    -v "concat('db_engine = ',db_engine)" -n \
    -v "concat('db_host = ',db_host)" -n \
    -v "concat('db_user = ',db_user)" -n \
    -v "concat('db_pass = ',db_pass)" -n \
    -v "concat('db_name = ',db_name)" -n \
    -v "concat('email_to = ',email_to)" -n \
    -v "concat('log_level = ',log_level)" -n \
    -o "greyhole_log_file = /var/log/greyhole.log" -n \
    -v "concat('delete_moves_to_trash = ',delete_moves_to_trash)" -n \
    -v "concat('balance_modified_files = ',balance_modified_files)" -n \
    -v "concat('df_cache_time = ',df_cache_time)" -n \
    -v "concat('log_memory_usage = ',log_memory_usage)" -n \
    -v "concat('check_for_open_files = ',check_for_open_files)" -n \
    -i "string-length(extraoptions) > 0" -v extraoptions -n \
    ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${GREYHOLE_CONFIG}