#!/bin/sh

# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Stephane Bocquet <stephane_bocquet@hotmail.com>
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c) 2011 Stephane Bocquet
# @copyright Copyright (c) 2011-2012 Marcel Beck
# @copyright Copyright (c) 2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

# Only if enabled
if [ "$(omv_config_get "//services/greyhole/enable")" != "1" ]; then
    exit 0
fi

GREYHOLE_CONFIG="/etc/greyhole.conf"

echo "#======================= Greyhole Shares =======================" >> ${GREYHOLE_CONFIG}

index=$(omv_config_get_count "//services/greyhole/smb_shares/share")
while [ ${index} -gt 0 ]
do
    # Get the shared folder reference and path
    smb_share_ref=$(omv_config_get "//services/greyhole/smb_shares/share[position()=${index}]/smbref")
    smb_share_num_copies=$(omv_config_get "//services/greyhole/smb_shares/share[position()=${index}]/num_copies")
    smb_share_name=$(omv_config_get "//services/smb/shares/share[uuid='${smb_share_ref}']/name")

    xmlstarlet sel -t -m "//services/greyhole/smb_shares/share[position()=${index}]" \
      -o "num_copies[${smb_share_name}] = ${smb_share_num_copies}" -n \
      -i "sticky_files[. = '1']" -o "sticky_files = ${smb_share_name}/" -b -n \
      -i "trash[. = '0']" -o "delete_moves_to_trash[${smb_share_name}] = no" -b -n \
      -i "trash[. = '1']" -o "delete_moves_to_trash[${smb_share_name}] = yes" -b -n \
      ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${GREYHOLE_CONFIG}

    index=$(( ${index} - 1 ))
done